### ISSUE TITLE
Client Protocol

### ISSUE THREAD

**Issue by Danielh21** [rpuls/CA-chat#13]

**Comment by rpuls** [comment]
The client understands all possible server messages now.

private void dispatchMsg(String msg) { // diispatches the message to onMsg or onClienList, and does nothing if the command is not rocognized
        String[] words = msg.split(":");
        switch (words[0]) {

```
        case "MSGRES":
            onMsg(words[1], words[2]);
            break;
        case "CLIENTLIST":
            onClientList(words[1]);
            break;
    }
}
```

see methods onClientList() and onMsg()

**Comment by Danielh21** [comment]
Nice!
